import logic
import models


class Manager:
    def create_room(self, room_id): ...

    def add_player(self, room_id, player): ...

    def remove_player(self, room_id, player): ...

    def list_players(self, room_id): ...

    def start_game(self, room_id): ...

    def end_game(self, room_id): ...

    def reset_game(self, room_id): ...

    def generate_question(self, room_id): ...

    def submit_answer(self, room_id, player, answer): ...

    def update_score(self, room_id, player, correct): ...

    def broadcast_state(self, room_id): ...
